package workshop2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class Excercise {

	private int id;
	private String title;
	private String description;

	public Excercise(String title, String description) {
		this.title = title;
		this.description = description;
	}

	public Excercise() {
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getId() {
		return id;
	}

	public void saveToDB(Connection conn) throws SQLException {
		if (this.id == 0) {
			String sql = "INSERT INTO excercise (title, description) VALUES (?, ?);";
			String autoGeneratedKeys[] = { "ID" };
			PreparedStatement prepStat = conn.prepareStatement(sql, autoGeneratedKeys);
			prepStat.setString(1, this.title);
			prepStat.setString(2, this.description);
			prepStat.executeUpdate();
			ResultSet rs = prepStat.getGeneratedKeys();
			if (rs.next()) {
				this.id = rs.getInt(1);
			}
		} else {
			String sql = "UPDATE excercise SET title=?, description=? WHERE ID = ?;";
			PreparedStatement prepStat = conn.prepareStatement(sql);
			prepStat.setString(2, this.title);
			prepStat.setString(3, this.description);
			prepStat.setInt(3, this.id);
			prepStat.executeUpdate();
		}
	}

	static public Excercise loadExcerciseById(Connection conn, int id) throws SQLException {
		String sql = "SELECT * FROM excercise WHERE id=?;";
		PreparedStatement prepStat = conn.prepareStatement(sql);
		prepStat.setInt(1, id);
		ResultSet rs = prepStat.executeQuery();
		if (rs.next()) {
			Excercise excercise = new Excercise();
			excercise.id = rs.getInt(1);
			excercise.title = rs.getString(2);
			excercise.description = rs.getString(3);
			return excercise;
		}
		return null;
	}

	@Override
	public String toString() {
		return "Excercise [id=" + id + ", title=" + title + ", description=" + description + "] \n";
	}

	static public List<Excercise> loadAllExcercises (Connection conn) throws SQLException {
		ArrayList<Excercise> excercises = new ArrayList<Excercise>();
		String sql = "SELECT * FROM excercise;";
		PreparedStatement prepStat = conn.prepareStatement(sql);
		ResultSet rs = prepStat.executeQuery();
		while (rs.next()) {
			Excercise excercise = new Excercise();
			excercise.id = rs.getInt(1);
			excercise.title = rs.getString(2);
			excercise.description = rs.getString(3);
			excercises.add(excercise);
		}
		return excercises;
	}
	
	public void delete(Connection conn) throws SQLException {
		if (this.id != 0) {
			String sql = "DELETE FROM excercise WHERE id = ?;";
			PreparedStatement prepStat = conn.prepareStatement(sql);
			prepStat.setInt(1, this.id);
			prepStat.executeUpdate();
			this.id=0;
		}
	}
}
